name: cua_hang_hoa_sen_da
description: "A new Flutter project cho cửa hàng hoa sen đá."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  sqflite: ^2.4.1
  path: ^1.9.0
  provider: ^6.1.1
  sqflite_common_ffi: ^2.3.3
  google_maps_flutter: ^2.12.3
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700